### ISSUE TITLE
Using System, adding documents, stopped, can't start, disabled com.alvexcore.repo.inform-policy

### ISSUE THREAD

**Issue by deadmike** [ITDSystems/alvex#14]
[solr.went.bad.log](https://github.com/ITDSystems/alvex/files/1594132/solr.went.bad.log)
[alfresco.went.bad.log](https://github.com/ITDSystems/alvex/files/1594133/alfresco.went.bad.log)
[share.wentbad.log](https://github.com/ITDSystems/alvex/files/1594134/share.wentbad.log)

will not boot up, system was up and operating fine. I stopped to add smtp configuration and upon startup, this issue. I disabled com.alvexcore.repo.inform-policy jar from loading to boot up, of course without the something, not sure, it seems to work ok, lost some site third column layout...

can send whatever you need. these are the logs when it went bad.

**Comment by aviriel** [comment]
According to your logs system could not start because you used prefix Namespace wfl in some script, but this namespace prefix is not defined in any model ("Namespace prefix wfl is not mapped to a namespace URI"). I suppose that together with removing inform-policy component you changed something else, because we don't know anything about this prefix, it's not a part of Alvex, and we cannot reproduce your bug on Alfresco 5.2.
