### ISSUE TITLE
Provide example for maven configuration and add release publishsing

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [ITDSystems/alvex#6]
I included your addon with following maven configuration:

        
        <dependency>
            <groupId>com.alvexcore.repo</groupId>
            <artifactId>uploader</artifactId>
            <version>1.37-SNAPSHOT</version>
            <classifier>installable</classifier>
        </dependency>

        
        <dependency>
            <groupId>com.alvexcore.share</groupId>
            <artifactId>uploader</artifactId>
            <version>1.37-SNAPSHOT</version>
            <classifier>installable</classifier>
        </dependency>

    <repositories>
        <repository>
            <id>alvex-public</id>
            <url>http://nexus.itdhq.com/content/repositories/snapshots/</url>
        </repository>
    </repositories>

First of all is it correct? If yes could you please include this as example for maven configuration. Also why do not build release version for your jars? I think it is good to publish them and avoid dependending on snapshots.

**Comment by aviriel** [comment]
1. Your configuration is correct except one point: if you include uploader, then you should also include https://github.com/ITDSystems/alvex-utils because uploader depends on it and will not start without it. If you did it, then it's absolutely correct.
2. We don't release jar-s because they are in development mode and are not ready to be used in production from our point of view. As soon as we can confirm that they are stable enough, we will release them.

**Comment by aviriel** [comment]
Added sample to the README, thanks!
https://github.com/ITDSystems/alvex/blob/master/README.md#include-alvex-to-another-project-via-maven-configuration

**Comment by C-h-e-r-r-y** [comment]
> Your configuration is correct except one point: if you include uploader, then you should also include https://github.com/ITDSystems/alvex-utils because uploader depends on it and will not start without it. If you did it, then it's absolutely correct.

No, including uploader leads to include all it's dependencies. Maven automatically adds them.
